[source.crates-io]
replace-with = "vendored-sources"

[source."git+https://github.com/extendr/extendr"]
git = "https://github.com/extendr/extendr"
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"